version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery worker -A happinesspackets -l info
    links:
      - redis
